name: sisater_mobile
description: "Sisater Mobile"


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  enviroment_flavor: ^2.0.3
  flutter_launcher_icons: ^0.14.1
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^5.0.3
  shared_preferences: ^2.0.11
  flutter_debouncer: ^2.0.0
  file_picker: ^8.1.4
  flutter_image_compress: ^2.0.1
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  fluttertoast: ^8.2.4
  esig_utils: ^5.4.1
  flutter_slider_drawer: ^2.1.3
  shimmer: ^3.0.0
  validadores: ^1.0.9
  intl: any
  mobx: ^2.0.1
  flutter_mobx: ^2.1.0+1
  one_context: ^4.0.0
  flutter_localizations:
    sdk: flutter
  loading_empty_error: ^3.4.4
  dio: ^5.3.3
  geocoding: ^3.0.0
  location: ^7.0.1
  mask_text_input_formatter: ^2.5.0
  flutter_animate: ^4.2.0+1
  pdf: ^3.10.6
  path_provider: ^2.0.0
  device_info_plus: ^11.1.1
  animated_checkmark: ^3.1.0
  flutter_multi_formatter: ^2.12.1
  flutter_svg: ^2.0.10+1
  email_validator: ^3.0.0
  logger: ^2.6.0
  firebase_crashlytics: ^4.1.5
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.5
  open_file: ^3.2.1
  flutter_pdfview: ^1.3.2
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2




dev_dependencies:
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imagens_video/

